#!/usr/bin/env bash
# This script modifies /etc/hosts to remap localhost and facebook.com
sudo sed -i 's/127.0.0.1\tlocalhost/127.0.0.2\tlocalhost/' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts